# -*- coding:utf-8 -*-

from enum import Enum, auto


class eErrorCode(Enum):
    ExcuteSuccess = 1000  # ///<执行任务成功
    ExcuteFailed = auto()  # ///<执行任务失败 - 系统错误
    DeclaredDone = auto()  # ///<已申报
    NoNeedDeclare = auto()  # ///<无需申报
    EmptyTable = auto()  # ///<申报表数据为空
    EmptyTableCel = auto()  # ///<单元格数据为空
    ExcuteFailedUser = auto()  # ///<执行任务失败 - 用户问题
    ExcuteFailedTaxation = auto()  # ///<执行任务失败 - 税局问题
    LoginUserPwdError = auto()  # ///<登录用户或密码错误
    LoginCaptchaError = auto()  # ///<验证码错误
    CaLoginError = auto()  # ///<CA登陆错误
    CaPasswordError = auto()  # ///<CA密码错误
    CaPasswordLengthError = auto()  # ///<CA密码长度不符
    CaLocked = auto()  # ///<CA已锁定
    CaSelectError = auto()  # ///< 登陆时CA证书选择失败
    CAPageExpection = auto()  # ///<CA登录页面打开异常
    VpnConnectError = auto()  # ///<VPN链接失败
    VpnUserPwdError = auto()  # ///<VPN用户名或密码错误
    VpnUserPwdMismatch = auto()  # ///<VPN和用户名不匹配
    LoginPageExpection = auto()  # ///<用户名密码登录网页打开异常
    RunJScriptFailed = auto()  # ///<运行脚本失败
    OpenUrlFailed = auto()  # ///<打开页面失败
    UnExceptedUrl = auto()  # ///<异常页面
    ExceptionWindowDetailFailed = auto()  # ///<异常窗口处理失败
    AjaxHookFailed = auto()  # ///<Ajax hook失败
    CheckGroupReportTask = auto()  # ///<检验全量报表失败
    ErrorPreGroupNotDeclare = auto()  # ///<前置表套未申报
    ParseDataFailed = auto()  # ///<解析xml数据错误
    FillReportFailed = auto()  # ///<填写报表失败
    SaveDataFailed = auto()  # ///<表格保存失败
    SubmitFailed = auto()  # ///<提交表格数据失败
    UploadFileCompanyNameError = auto()  # ///<上传的文件不是本单位文件
    UploadFileMd5Error = auto()  # ///<上传文件md5校验错误
    UploadGenerateFileFailed = auto()  # ///<上传文件生成文件错误
    GenerateFileFailed = auto()  # ///<生成文件失败
    Browsetheselectionfilefailed = auto()  # ///<浏览选择文件失败
    CollectTableFailed = auto()  # ///<采集表格信息失败
    EnterTableFailed = auto()  # ///<登录报表失败
    FillCellFailed = auto()  # ///<数据填写失败
    VerifyCellFailed = auto()  # ///<校验失败
    TemporarySaveTableFailed = auto()  # ///<暂存报表失败
    StartAppFailed = auto()  # ///<启动客户端失败
    UnSupportedTask = auto()  # ///<不支持的任务
    HtmlElementNotExist = auto()  # ///<元素不存在
    NotInDeclarePeriod = auto()  # ///<不在申报期内
    AuthenticationFailed = auto()  # ///<没认证
    CopyingDutyFailed = auto()  # ///<没抄税
    FindTableFailed = auto()  # ///<没有找到此报表
    SubmitInvoiceFailedUnknown = auto()  # ///<发票提交失败原因未知
    NoTaskContext = auto()  # ///<无任务上下文
    InitDataError = auto()  # ///<初始化数据出错
    ErrorUnexpectedAlert = auto()  # ///<非预期的alert
    ErrorUnexpectedConfirm = auto()  # ///<非预期的confirm
    ErrorUnexpectedShowMessage = auto()  # ///<非预期的showmessage
    ErrorTimeDate = auto()  # ///<xml中无查询日期
    UploadFileFailed = auto()  # ///<上传文件失败
    CompanyInfoNotMath = auto()  # ///<公司信息不匹配
    EmptyGroup = auto()  # ///<表套数据为空
    AuditFailed = auto()  # ///<报表审核不通过
    NotSupportTaskGroup = auto()  # ///<不支持的TaskGroup
    LoadJavaScriptFailed = auto()  # ///<加载JavaScript失败
    LoginTypeError = auto()  # ///<登录类型错误
    BasicEnvironment = auto()  # ///<基础环境错误
    NssbReadError = auto()  # ///<读取纳税人基本信息错误
    TaxServiceException = auto()  # ///<税务局网站或者客户端异常
    TaxServiceUpdating = auto()  # ///<税务局系统正在维护中
    CompanyOldGSUnable = auto()  # ///<该公司已无法登录旧国税
    AddAppFailed = auto()  # ///<添加应用失败
    SignError = auto()  # ///<电子签名失败
    ManualCloseWindows = auto()  # ///<用户手动关闭申报采集窗口
    OperationTimeOut = auto()  # ///<操作超时
    UserNotExist = auto()  # ///<用户名不存在
    JSGSSZRDEmpty = auto()  # ///<用户在江苏旧国税的税种认定为空
    SBReportDataEmpty = auto()  # ///<地税社保申报表没有数据
    LoginTimeOutError = auto()  # ///<打开税局网页超时,请稍后重试
    LoginNoCA = auto()  # ///<登陆时本地没有CA证书
    LoginCAUnMatch = auto()  # ///<登陆时本地CA证书不匹配
    MobileNumberCheckFailed = auto()  # ///<手机后四位校验失败，请检查
    SBServiceNoOpened = auto()  # ///<申报服务未开通，请联系4008012366
    LoginCAOverdue = auto()  # ///<CA证书失效或过期
    PaymentAmountError = auto()  # ///<缴款金额错误
    AmountBalanceError = auto()  # ///<账户余额不足
    UserInfomationCheck = auto()  # /// 用户手动登录确认信息
    CollectAfterDeclared = auto()  # /// 增值税税种已提交无法采集发票
    CheckTaxMissing = auto()  # /// 报税检查时发现存在遗漏的必报报表
    CompanyQualificationError = auto()  # /// 企业资格错误
    DisplaySizeError = auto()  # ///< 分辨率设置失败
    SyncDataConflict = auto()  # ///< 同步数据冲突
    SyncDataError = auto()  # ///< 同步数据异常
    SwcshNotHasData = auto()  # ///< 税务初始化，未查询到历史申报数据（指定的月份内就没有数据）
    SwcshNotMatchData = auto()  # ///< 税务初始化，没有指定征期的数据（有数据，但是征期匹配不上）
    NeedUserDecide = auto()  # ///< 遇到需要用户决定的情况
    SubmitFailedNeedtoRetry = auto()  # ///< 提交表格数据失败，需要重试或重发任务
    UnAbleToRevoke = auto()  # ///< 此报表已无法点击撤销
    DeclaredDoneDataNoMatch = auto()  # ///< 此报表已申报过但申报金额不符
    HasNoMatchJDXXInfo = auto()  # ///< 税局上存在未匹配的鉴定信息
    HadRevokeDone = auto()  # ///< 税局上的报表已撤销成功
    NeedRecvReceipt = 90000,  # ///<申报任务需要收取回执
    HZTaskSuccess = auto()  # ///<回执任务时任务结果成功 如申报成功等
    HZTaskFailed = auto()  # ///<回执任务时任务结果失败 如申报数据审核不通过等
    HZDeclaredDone = auto()  # ///<回执任务时任务结果已申报过
    GetReceiptFailed = auto()  # ///<回执任务时获取回执失败
    HZTaskContinue = auto()  # ///<已经的得到一种结果，还需要继续取回执
    ModemPoolConnectFailed = 95000  # ///<猫池连接失败
    ModemPoolPhoneNotExist = auto()  # ///<猫池手机号不存在
    ModemPoolLockPhoneTimeout = auto()  # ///<猫池手机号上锁超时
    ModemPoolGetCodeTimeout = auto()  # ///<猫池短信验证码获取超时
    Stm32InInitialization = 100001  # ///<stm32初始化中
    UsbPortNumOver = auto()  # ///<超出USB物理端口数量
    InitEnumFailed = auto()  # ///<该单板初始化时，未能枚举
    OpenPortFailed = auto()  # ///<stm32打开端口失败
    UsbDeviceNumberOver = auto()  # ///<Usb bus设备数目超限
    SerachDevicesOnUsbFailed = auto()  # ///<Usb 端口上未能找到设备
    Stm32TimeOut = auto()  # ///<Stm32在规定时间内没有应答
    Stm32ClosePortFailed = auto()  # ///<Stm32应答关闭端口失败
    Stm32VeneerFindFailed = auto()  # ///<Stm32 未能找到单板
    SerachDevicesOnStm32Failed = auto()  # ///<Stm32 未能找到设备
    ReadUsbTreeFailed = auto()  # ///<读usb树失败
    FindCorrespondingVeneerFailed = auto()  # ///<没有找到对应的单板
    PortHaveUsed = auto()  # ///<该端口已经使用
    SetStartNonzero = auto()  # ///<设置起始号不能为0
    ServiceUsbPortFull = auto()  # ///<服务器USB端口已经满了
    NoRightClosePort = auto()  # ///<无权关闭该端口
    OpenServiceNonRootAccount = auto()  # ///<服务开启服务非root账户
    RegUsbIPKOFailed = auto()  # ///<注册usbip.ko失败
    RegSTM32Failed = auto()  # ///<注册STM32失败
    CommandTimeout = auto()  # ///<命令超时
    NoRespondRequests = auto()  # ///<获取服务器信息，不能响应客户请求
    DatalengthError = auto()  # ///<数据长度错误
    CommandExecuting = auto()  # ///<有命令正在执行,请等待命令结束
    OpenPortOverMax = auto()  # ///<打开端口已经达到最大值
    PortError = auto()  # ///<端口号错误，未能查找到端口号所在的USB服务器
    ConnectServerFailed = auto()  # ///<连接服务器失败，服务没有启动或者服务器忙
    UndefinedCommandProtocol = auto()  # ///<命令协议未定义
    ParameterError = auto()  # ///<参数错误
    UsbiPost = auto()  # ///<usbip.exe丢失
    UsbipRun_timeError = auto()  # ///<usbip.exe运行错误
    QueryUsedPortFailed = auto()  # ///<查询已使用端口失败
    UsbipPortStatusQueryFailed = auto()  # ///<usbip共享端口状态查询失败
    OpenVbusFailed = auto()  # ///<打开vbus失败
    ReadPortStatusFailed = auto()  # ///<读端口状态失败
    TcpConnFailed = auto()  # ///<Tcp连接失败
    NoConBusid = auto()  # ///<连接的busid不存在
    NoVbusPortVaild = auto()  # ///<Vbus无端口可用
    AllocateMemoryFailed = auto()  # ///<分配内存失败
    CreateEventsFailed = auto()  # ///<创建事件失败
    ErrorUnknownCabinetPos = auto()  # ///<机柜位置错误未知错误
    StartPortNotEqualEnd = auto()  # ///<打开关闭USB共享单元端口起始端口和结束端口不等
    ReadCAInfoFailed = auto()  # ///<打开端口后读取证书信息失败
    ClientConnectTimeout = 200002  # ///<客户端连接超时
    ClientTaskExecuteTimeout = auto()  # ///<客户端任务执行超时
    CreateOpenPortTaskFailed = auto()  # ///<创建打开USB端口任务失败
    CreateClosePortTaskFailed = auto()  # ///<创建关闭USB端口任务失败
    GetTaskTimeout = auto()  # ///<客户端获取任务超时
    ManualReturnResult = auto()  # ///<用户手动点击返回任务结果
    ExecutLimit = auto()  # ///<任务执行次数达到最大限制（客户端没有返回）,请重试
    SyncNotNeedDownload = auto()  # ///<该企业数据已经下载，无需下载
    SyncNeedUploadLast = auto()  # ///<存在未上传的企业
    WaitForRetry = 300000  # ///<任务执行失败，需要进行重试
    UnknownErr = 999999  # ///<未知错误
